dev/secureshare/home/urls.py
from django.conf.urls import include, url

from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView, name='home'),
]

dev/secureshare/reports/urls.py
from django.conf.urls import include, url

from . import views


urlpatterns = [
    url(r'^register/(?P<folder_id>[0-9]+)/$', views.register_report, name='register_report'),

    url(r'^file/download/(?P<file_id>[0-9]+)/$', views.download_file, name='download_file'),
    url(r'^file/delete/(?P<file_id>[0-9]+)/$', views.delete_file, name='delete_file'),
    url(r'^file/all_documents/$', views.all_documents, name='all_documents'),

    url(r'^report/(?P<pk>[0-9]+)/$', views.ReportDetailView.as_view(), name='view_report'),
    url(r'^report/(?P<report_id>[0-9]+)/edit/$', views.edit_report, name='edit_report'),
    url(r'^report/(?P<report_id>[0-9]+)/delete/$', views.delete_report, name='delete_report'),
    url(r'^report/(?P<report_id>[0-9]+)/download/$', views.download_report, name='download_report'),
    url(r'^report/(?P<report_id>[0-9]+)/upload_file/$', views.upload_file_to_report, name='upload_file_to_report'),
    url(r'^report/(?P<report_id>[0-9]+)/favorite/$', views.favorite_report, name='favorite_report'),

    url(r'^folder/(?P<folder_id>[0-9]+)/$', views.view_folder, name='view_folder'),
    url(r'^folder/(?P<folder_id>[0-9]+)/new/$', views.new_folder, name='new_folder'),
    url(r'^folder/(?P<folder_id>[0-9]+)/delete/$', views.delete_folder, name='delete_folder'),

    url(r'^all_reports/$', views.all_reports, name='all_reports'),
    url(r'^all_reports/detail/$', views.all_reports, name='all_reports_detail'),
    url(r'^my_reports/$', views.MyReportListView.as_view(), name='my_reports'),
    url(r'^favorites/$', views.view_favorites, name='view_favorites'),
    url(r'^search/$', views.search, name='search'),
]

dev/secureshare/secureshare/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^messages/', include('postman.urls', namespace='postman')),
]

dev/secureshare/users/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'users:login'}, name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^change_password/$', change_password, name='change-password'),



    url(r'^create_group/$', create_group, name='create_group'),
    url(r'^join_group/$', join_group, name='join_group'),
    url(r'^leave_group/$', leave_group, name='leave_group'),
    #url(r'^invite/$', invite_user, name='invite_user'),


    url(r'^all_users/$', all_users, name='all_users'),
    url(r'^all_groups/$', all_groups, name='all_groups'),
    url(r'^my_groups/$', my_groups, name='my_groups'),

    url(r'^user/(?P<user_id>[0-9]+)/$', view_user, name='user'),
    url(r'^group/(?P<group_id>[0-9]+)/$', view_group, name='group'),

    url(r'^group/(?P<group_id>[0-9]+)/leave/(?P<user_id>[0-9]+)/$', leave_group_by_id, name='leave_group_by_id'),

    url(r'^user/(?P<user_id>[0-9]+)/suspend/$', suspend_user, name='suspend_user'),
    url(r'^user/(?P<user_id>[0-9]+)/promote/$', promote_user, name='promote_user'),
    url(r'^user/(?P<user_id>[0-9]+)/(?P<group_id>[0-9]+)/remove_from_group/$', remove_user_from_group, name='remove_user_from_group'),
    url(r'^user/(?P<group_id>[0-9]+)/add_user_to_group/$', add_user_to_group, name='add_user_to_group'),

]

'''
url(r'^inbox/$', inbox, name='inbox'),
url(r'^outbox/$', outbox, name='outbox'),
url(r'^send_message/$', send_message, name='send_message'),
'''

dev/secureshare/users/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import PermissionDenied
from django.utils.translation import gettext as _

from .models import User
from django.contrib.auth.models import Group

from django.shortcuts import get_object_or_404

class JoinGroupForm(forms.Form):
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.exclude(isPrivate=True), widget=forms.CheckboxSelectMultiple(), required=False, initial=Group.objects.all())

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(JoinGroupForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        for group in self.cleaned_data['groups']:
            g = Group.objects.get(name=group.name)
            self.user.groups.add(g)
        if commit:
            self.user.save()

        return self.user

class AddUserToGroupForm(forms.Form):
    users = forms.ModelMultipleChoiceField(queryset=User.objects.all(), widget=forms.CheckboxSelectMultiple(), required=False)

    def __init__(self, *args, **kwargs):
        super(AddUserToGroupForm, self).__init__(*args, **kwargs)

    def save(self, group_id):
        g = Group.objects.get(id=group_id)
        for user in self.cleaned_data['users']:
            u = User.objects.get(id=user.id)
            print(u)
            u.groups.add(g)
            u.save()

        return g

class LeaveGroupForm(forms.Form):
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), widget=forms.CheckboxSelectMultiple(), required=False, initial=Group.objects.all())

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(LeaveGroupForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        for group in self.cleaned_data['groups']:
            g = Group.objects.get(name=group.name)
            self.user.groups.remove(Group.objects.get(name=g))
        if commit:
            self.user.save()

        return self.user

class CreateGroupForm(forms.Form):
    name = forms.CharField(max_length=80)
    description = forms.CharField(label='\nDescription', max_length=140, required=False, widget=forms.Textarea)
    private = forms.BooleanField(required=False)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(CreateGroupForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        try:
            Group.objects.get(name=self.cleaned_data['name'])
            raise forms.ValidationError("Group with this name already exists")
        except Group.DoesNotExist:
            pass
        return self.cleaned_data['name']

    def save(self, commit=True):
        Group.objects.get_or_create(name=self.cleaned_data['name'], description=self.cleaned_data['description'], isPrivate=self.cleaned_data['private'])
        g = Group.objects.get(name=self.cleaned_data['name'])
        self.user.groups.add(g)
        if commit:
            self.user.save()
        return self.user

class RegisterUserForm(forms.Form):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=40)
    last_name = forms.CharField(max_length=40)
    password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password (again)"), widget=forms.PasswordInput)

    def clean_email(self):
        try:
            User.objects.get(email=self.cleaned_data['email'])
            raise forms.ValidationError("User with this email already exists")
        except User.DoesNotExist:
            pass
        return self.cleaned_data['email']

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(_("The two password fields didn't match."))
        return password2

    def save(self, commit=True):
        user = User.objects.create_normal_user(
            email=self.cleaned_data['email'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
        )
        user.set_password(self.cleaned_data['password1'])

        if commit:
            user.save()

        return user

'''
class SendMessageForm(forms.Form):
    receiver = forms.CharField(max_length=80)
    content = forms.CharField(max_length=80)

    def __init__(self, *args, **kwargs):
        super(SendMessageForm, self).__init__(*args, **kwargs)

    def save(self, sender):
        id = self.cleaned_data['receiver']
        receiver = get_object_or_404(User, pk=id)
        content = self.cleaned_data['content']
        msg = Message(
            sender=sender,
            receiver=receiver,
            msg_content=content
        )
        msg.save()
'''


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(label=_("Current Password"), widget=forms.PasswordInput)
    new_password1 = forms.CharField(label=_("New Password"), widget=forms.PasswordInput)
    new_password2 = forms.CharField(label=_("New Password (again)"), widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean_current_password(self):
        try:
            user = authenticate(email=self.user.email, password=self.cleaned_data['current_password'])
            if user is None:
                raise forms.ValidationError(_("Incorrect Password."))
        except PermissionDenied:
            raise forms.ValidationError(_("Incorrect Password."))

    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')
        if new_password1 and new_password2:
            if new_password1 != new_password2:
                raise forms.ValidationError(_("The two password fields didn't match."))
        return new_password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])

        if commit:
            self.user.save()

        return self.user

dev/secureshare/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages


from .forms import *
from .models import *
from reports.models import *


def register(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            rf = RootFolder(name=user.email, owner=user, is_root=True)
            rf.save()
            messages.success(request, user.email)
            return redirect('users:login')
    else:
        form = RegisterUserForm()
    form_title = 'Create New User'
    form_back = '/users/login/'
    form_action = '/users/register/'
    return render(request, 'users/general_form.html', {'form': form, 'form_title':form_title, 'form_back':form_back, 'form_action':form_action})


def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            update_session_auth_hash(request, user)
            return redirect('home:home')
    else:
        form = ChangePasswordForm(user=request.user, data=request.POST)
    form_title = 'Change password'
    form_back = request.META['HTTP_REFERER']
    form_action = '/users/change_password/'
    return render(request, 'users/general_form.html', {'form': form, 'form_title': form_title, 'form_back':form_back, 'form_action':form_action})


def join_group(request):
    if request.method == 'POST':
        form = JoinGroupForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            update_session_auth_hash(request, user)
            return redirect('home:home')
    else:
        form = JoinGroupForm(user=request.user, data=request.POST)
    form_title = 'Join New Group'
    form_back = request.META['HTTP_REFERER']
    form_action = '/users/join_group/'
    return render(request, 'users/general_form.html', {'form': form, 'form_title': form_title, 'form_back': form_back, 'form_action': form_action})


def leave_group(request):
    if request.method == 'POST':
        form = LeaveGroupForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            update_session_auth_hash(request, user)
            return redirect('home:home')
    else:
        form = LeaveGroupForm(user=request.user, data=request.POST)
    form_title = 'Join New Group'
    form_back = request.META['HTTP_REFERER']
    form_action = '/users/leave_group/'
    return render(request, 'users/general_form.html', {'form': form, 'form_title': form_title, 'form_back': form_back, 'form_action': form_action})


def leave_group_by_id(request, group_id, user_id):
    user = get_object_or_404(User, pk=user_id)
    group = get_object_or_404(Group, pk=group_id)
    if user == request.user or request.user.is_site_manager:
        if group in user.groups.all():
            user.groups.remove(group)
    return redirect('users:group', group_id=group_id)


def add_user_to_group(request, group_id):
    if request.method == 'POST':
        form = AddUserToGroupForm(data=request.POST)
        if form.is_valid():
            form.save(group_id=group_id)
            return redirect('users:all_groups')
    else:
        form = AddUserToGroupForm(data=request.POST)
    form_title = 'Add User To Group'
    form_back = '/users/all_groups/'
    form_action = '/users/user/' + str(group_id) + '/add_user_to_group/'
    return render(request, 'users/general_form.html',
                  {'form': form, 'form_title': form_title, 'form_back': form_back, 'form_action': form_action})


def create_group(request):
    if request.method == 'POST':
        form = CreateGroupForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            update_session_auth_hash(request, user)
            return redirect('home:home')
    else:
        form = CreateGroupForm(user=request.user, data=request.POST)
    form_title = 'Create New Group'
    form_back = request.META['HTTP_REFERER']
    form_action = '/users/create_group/'
    return render(request, 'users/general_form.html', {'form':form, 'form_title':form_title, 'form_back':form_back,'form_action':form_action})


def view_group(request, group_id):
    template_name = 'users/view_group.html'
    group = get_object_or_404(Group, pk=group_id)

    context = {}
    context['group'] = group
    users = []
    for user in User.objects.all():
        if group in user.groups.all():
            users.append(user)
    context['viewed_users'] = users
    context['user'] = request.user
    context['user_in_group'] = group in request.user.groups.all()

    return render(request, template_name, context)


def view_user(request, user_id):
    template_name = 'users/view_user.html'
    user = get_object_or_404(User, pk=user_id)

    context = {}
    context['viewed_user'] = user
    context['groups'] = user.groups.all()
    context['reports'] = Report.objects.filter(owner=user)

    return render(request, template_name, context)


def suspend_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.user.is_site_manager:
        user.is_suspended = not user.is_suspended
        user.save()
    return redirect('users:user', user_id=user.id)


def promote_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.user.is_site_manager:
        user.is_site_manager = not user.is_site_manager
        user.save()
    return redirect('users:user', user_id=user.id)


def remove_user_from_group(request, user_id, group_id):
    user = get_object_or_404(User, pk=user_id)
    if request.user.is_site_manager:
        g = Group.objects.get(id=group_id)
        user.groups.remove(g)
    if '/user/' in request.META['HTTP_REFERER']:
        return redirect('users:user', user_id=user_id)
    elif '/group/' in request.META['HTTP_REFERER']:
        return redirect('users:group', group_id=group_id)
    else:
        return redirect('home:home')


def my_groups(request):
    template_name = 'users/my_groups.html'

    context = {}
    context['groups'] = request.user.groups.all()

    return render(request, template_name, context)


def all_groups(request):
    template_name = 'users/all_groups.html'

    context = {}
    context['groups'] = Group.objects.all()

    return render(request, template_name, context)


def all_users(request):
    template_name = 'users/all_users.html'

    context = {}
    context['users'] = User.objects.all()

    return render(request, template_name, context)



'''
def inbox(request):
    template_name = 'users/inbox.html'
    message_set = Message.objects.inbox(request.user)
    return render(request, template_name, {'message_set': message_set},)


def outbox(request):
    template_name = 'users/outbox.html'

    context = {}
    context['users'] = User.objects.all()

    return render(request, template_name, context)



def send_message(request):
    if request.method == 'POST':
        form = SendMessageForm()
        if form.is_valid():
            form.save(sender=request.user)
            return redirect('users:profile')

    else:
        form = SendMessageForm()
    form_title = 'Send New Message'
    form_back = '/users/outbox/'
    form_action = '/users/outbox/'
    return render(request, 'users/general_form.html',
                  {'form': form, 'form_title': form_title, 'form_back': form_back, 'form_action': form_action})
'''

dev/secureshare/users/templates/users/general_form.html
{% extends 'home/base.html' %}

{% block content %}

<h1><a href={{ form_back }}><small><span class="glyphicon glyphicon-menu-left" style="color:white;"></span></small></a>  {{ form_title }}</h1>
<hr/>
<form method='POST' action={{ form_action }} >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-default" value="submit" />
</form>

{% endblock %}

dev/secureshare/users/templates/users/inbox.html
{% extends 'home/base.html' %}

{% block content %}

{% if user.is_authenticated %}
    Inbox for {{ user.id }}

    <p>Messages:</p>
    <ul>
    {% if message_set %}
        {% for message in message_set %}
            <li>
                <strong>{{ message.msg_content }}</strong>
            </li>
        {% endfor %}
    {% else %}
        <li>
            <strong>You currently have no messages</strong>
        </li>
    {% endif %}
    </ul>

{% else %}
    <p>You are not logged in, so you can't see your profile</p>
{% endif %}

{% endblock %}

dev/secureshare/users/templates/users/login.html
{% extends 'home/base.html' %}

{% block content %}
<div class="row">
    <div class="col-xs-8 col-centered">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                  <strong>Well Done!</strong>
                    User {{ message }} has been created!
                </div>
            {% endfor %}
        {% endif %}

        {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
        {% endif %}


        {% if user.is_authenticated %}
        <p>You are already logged in</p>
        {% else %}
        <h1>Login</h1>

        <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
            <div class="form-group">
                <label class="sr-only" for="id_username">Email</label>
                <input type="email" class="form-control" id="id_username" name="username" placeholder="Email">
            </div>
            <div class="form-group">
                <label class="sr-only" for="id_password">Password</label>
                <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Login</button>
            <input type="hidden" name="next" value="{% url 'home:home' %}" />
        </form>
        <br>
        Need an account? Register <a href="{% url 'users:register' %}">here</a>
        {% endif %}
    </div>
</div>
{% endblock %}

dev/secureshare/users/templates/users/my_groups.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-xs-12 col-centered">
            {% if user.is_authenticated %}
                <div class="list-group">
                    <li class="list-group-item list-group-item-info">
                        Your Groups:

                        <a href="{% url 'users:leave_group' %}" class="pull-right">
                            <small>LEAVE</small>
                        </a>
                        <a href="{% url 'users:join_group' %}" class="pull-right">
                            <small>JOIN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>
                        </a>
                        <a href='' data-toggle="modal" data-target="#newGroupModal" class="pull-right">
                            <span class="glyphicon glyphicon-plus">&nbsp;</span>
                        </a>
                    </li>
                    {% if groups %}
                        {% for group in groups %}
                            <a href="{% url 'users:group' group_id=group.id %}" class="list-group-item list-group-item-action">
                                {{ group.name }}
                                {% if group.isPrivate %}
                                <span class="pull-right glyphicon glyphicon-eye-close">&nbsp;</span>
                                {% endif %}
                            </a>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item">You are not in any groups.</li>
                    {% endif %}
                </div>
            {% else %}
            <p>You must login to view this page.</p>
            {% endif %}
        </div>
    </div>

<div class="modal fade" id="newGroupModal" role="dialog">
    <div class="modal-dialog">
          <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="border-bottom: none;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New Group</h4>
            </div>
            <form action="{% url 'users:create_group' %}" method="post">
            <div class="modal-body">
                {% csrf_token %}
                <label for="id_name">Name:</label> <input id="id_name" maxlength="80" name="name" type="text" required />
                <br>
                <label for="id_description">
Description:</label> <textarea cols="40" id="id_description" maxlength="140" name="description" rows="4" class="form-control">
</textarea>
                <br>
                <label for="id_private">Private:</label> <input id="id_private" name="private" type="checkbox" />
            </div>
            <div class="modal-footer" style="border-top: none;">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <input type="submit" value="Create" class="btn btn-primary">
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

dev/secureshare/users/templates/users/outbox.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 col-md-8 col-lg-8 col-centered">
            {% if user.is_authenticated %}
                <div class="list-group">
                    <li class="list-group-item list-group-item-info">All Users:</li>
                    {% if users %}
                        {% for user in users %}
                            <a href="{% url 'users:send_message' %}" class="list-group-item list-group-item-action">{{ user.first_name }} {{ user.last_name }}</a>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item">There are no users.</li>
                    {% endif %}
                </div>
            {% else %}
            <p>You do not have permission to view this page.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

dev/secureshare/users/templates/users/view_group.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-xs-12 col-centered">
            {% if user.is_authenticated %}
                <div class="list-group">
                    <li class="list-group-item text-center">
                        <h2>
                            <span class="pull-left"><small>group:</small></span>
                            {{ group.name }}
                        </h2>
                    </li>
                </div>
                <br>
                <div class="list-group">
                    <li class="list-group-item">
                        {% if group.isPrivate %}
                        This group is private.
                        {% else %}
                        This group is not private
                        {% endif %}
                    </li>
                    <li class="list-group-item">
                        <strong>Description: </strong>{{group.description}}
                    </li>
                </div>
            <br>
                <div class="list-group">
                    <li class="list-group-item list-group-item-info">Members in this group:</li>
                    {% if viewed_users %}
                        {% for viewed_user in viewed_users %}
                            {% if user.is_site_manager %}
                                <li class="list-group-item">
                                    <a href="{% url 'users:user' user_id=viewed_user.id %}" class="">{{ viewed_user.first_name }} {{ viewed_user.last_name }}</a>
                                    <a href="{% url 'users:remove_user_from_group' user_id=viewed_user.id group_id=group.id%}" class="pull-right">
                                        <span class="glyphicon glyphicon-remove" style="color:#c71500;"></span>
                                    </a>
                                </li>
                            {% else %}
                                <a href="{% url 'users:user' user_id=viewed_user.id %}" class="list-group-item list-group-item-action">{{ viewed_user.first_name }} {{ viewed_user.last_name }}</a>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item">There are no users in this group.</li>
                    {% endif %}
                </div>
                <br>
                <div class=list-grou"p>
                {% if user.is_site_manager %}
                    <a href="{% url 'users:add_user_to_group' group_id=group.id %}" class="list-group-item list-group-item-action">Add a user to this group</a>
                {% endif %}
                {% if user_in_group %}
                    <a href="{% url 'users:leave_group_by_id' group_id=group.id user_id=user.id %}" class="list-group-item list-group-item-action list-group-item-danger" style="color:red;">Leave this group</a>
                {% endif %}
                 </div>
            {% else %}
            <p>You do not have permission to view this page.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

dev/secureshare/users/templates/users/view_user.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-xs-12 col-centered">
            {% if user.is_authenticated %}
                <div class="list-group">
                    <li class="list-group-item text-center">
                        <h2>
                            <span class="pull-left"><small>user:</small></span>
                            {{ viewed_user.first_name }} {{ viewed_user.last_name }}
                        </h2>
                    </li>
                    {% if viewed_user.is_site_manager %}
                    <li class="list-group-item list-group-item-success"><small>SITE MANAGER</small></li>
                    {% endif %}

                    {% if viewed_user.is_suspended %}
                    <li class="list-group-item list-group-item-danger"><small>SUSPENDED</small></li>
                    {% endif %}
                </div>
                <br>
                <div class="list-group">
                    <li class="list-group-item list-group-item-info">Groups this user is in:</li>
                    {% if groups %}
                        {% for group in groups %}
                            {% if user.is_site_manager %}
                                <li class="list-group-item">
                                    <a href="{% url 'users:group' group_id=group.id %}">{{ group.name }}</a>
                                    <a href="{% url 'users:remove_user_from_group' user_id=viewed_user.id group_id=group.id%}" class="pull-right">
                                        <span class="glyphicon glyphicon-remove" style="color:#c71500;"></span>
                                    </a>
                                </li>
                            {% else %}
                                <a href="{% url 'users:group' group_id=group.id %}" class="list-group-item list-group-item-action">{{ group.name }}</a>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item">This user is in no groups.</li>
                    {% endif %}
                </div>
                <br>
                <div class="list-group">
                    <li class="list-group-item list-group-item-info">Reports by this user:</li>
                    {% if reports %}
                        {% for report in reports %}
                                <li class="list-group-item">
                                    <a href="{% url 'reports:view_report' pk=report.id %}">{{ report.title }}</a>
                                </li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item">This user has no reports.</li>
                    {% endif %}
                </div>
            {% else %}
            <p>You must login to view this page.</p>
            {% endif %}
            <br>
            {% if user.is_site_manager %}
                {% if viewed_user.is_suspended %}
                <a href="{% url 'users:suspend_user' user_id=viewed_user.id %}" role="button" class="btn btn-danger btn-lg">Remove suspension</a>
                {% else %}
                <a href="{% url 'users:suspend_user' user_id=viewed_user.id %}" role="button" class="btn btn-danger btn-lg">Suspend this user</a>
                {% endif %}

                {% if viewed_user.is_site_manager %}
                <a href="{% url 'users:promote_user' user_id=viewed_user.id %}" role="button" class="btn btn-danger btn-lg">Demote user</a>
                {% else %}
                <a href="{% url 'users:promote_user' user_id=viewed_user.id %}" role="button" class="btn btn-danger btn-lg">Promote user</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}