dev/secureshare/home/urls.py
from django.conf.urls import include, url

from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView, name='home'),
]

dev/secureshare/reports/urls.py
from django.conf.urls import include, url

from . import views


urlpatterns = [
    url(r'^register/(?P<folder_id>[0-9]+)/$', views.register_report, name='register_report'),

    url(r'^file/download/(?P<file_id>[0-9]+)/$', views.download_file, name='download_file'),
    url(r'^file/delete/(?P<file_id>[0-9]+)/$', views.delete_file, name='delete_file'),
    url(r'^file/all_documents/$', views.all_documents, name='all_documents'),

    url(r'^report/(?P<pk>[0-9]+)/$', views.ReportDetailView.as_view(), name='view_report'),
    url(r'^report/(?P<report_id>[0-9]+)/edit/$', views.edit_report, name='edit_report'),
    url(r'^report/(?P<report_id>[0-9]+)/delete/$', views.delete_report, name='delete_report'),
    url(r'^report/(?P<report_id>[0-9]+)/download/$', views.download_report, name='download_report'),
    url(r'^report/(?P<report_id>[0-9]+)/upload_file/$', views.upload_file_to_report, name='upload_file_to_report'),
    url(r'^report/(?P<report_id>[0-9]+)/favorite/$', views.favorite_report, name='favorite_report'),

    url(r'^folder/(?P<folder_id>[0-9]+)/$', views.view_folder, name='view_folder'),
    url(r'^folder/(?P<folder_id>[0-9]+)/new/$', views.new_folder, name='new_folder'),
    url(r'^folder/(?P<folder_id>[0-9]+)/delete/$', views.delete_folder, name='delete_folder'),

    url(r'^all_reports/$', views.all_reports, name='all_reports'),
    url(r'^all_reports/detail/$', views.all_reports, name='all_reports_detail'),
    url(r'^my_reports/$', views.MyReportListView.as_view(), name='my_reports'),
    url(r'^favorites/$', views.view_favorites, name='view_favorites'),
    url(r'^search/$', views.search, name='search'),
]

dev/secureshare/secureshare/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^messages/', include('postman.urls', namespace='postman')),
]

dev/secureshare/reports/models.py
from django.db import models
from datetime import *
from users.models import *


# Create your models here.
class Folder(models.Model):

    name = models.CharField(max_length=50, default="")
    is_root = models.BooleanField(default=False)


class RootFolder(Folder):

    owner = models.OneToOneField(User, related_name="root_folder")


class SubFolder(Folder):

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    parent_folder = models.ForeignKey(Folder, related_name="sub_folder")


class Report(models.Model):

    title = models.TextField(default="None", max_length= 50)
    short_description = models.TextField(default="", max_length=200)
    detailed_description = models.TextField(default="", max_length=5000)
    timestamp = models.DateTimeField(auto_now_add=True)

    view_count = models.IntegerField(default=0)

    owner = models.ForeignKey('users.User', on_delete=models.CASCADE)
    favorited_by = models.ManyToManyField(User, related_name="favorites")
    is_private = models.BooleanField(default=False)

    parent_folder = models.ForeignKey(Folder, related_name="reports")

    def has_access(self, user):
        if not self.is_private:
            return True
        if user.is_authenticated:
            if user.is_site_manager or self.owner == user:
                return True
        return False


class FileUpload(models.Model):

    title = models.TextField(default='title')
    file = models.FileField(default=None)
    timestamp = models.DateTimeField(auto_now_add=True)
    encrypted = models.BooleanField(default=False)
    report = models.ForeignKey(Report, related_name='files')
    # uploads must be given reports upon creation

# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

@receiver(pre_delete, sender=FileUpload)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.file.delete(False)

dev/secureshare/reports/forms.py
from django import forms
from django.forms import ModelForm
from .models import Report


class UploadFileForm(forms.Form):
    encrypted = forms.BooleanField(required=False)
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)


class ReportForm(forms.Form):
    title = forms.CharField(max_length=50, min_length=3)
    short_description = forms.CharField(max_length=200, required=False)
    detailed_description = forms.CharField(max_length=5000, required=False)
    is_private = forms.BooleanField(required=False)


"""
class Report(models.Model):
    report_id = models.AutoField(primary_key=True, default=0)
    title = models.TextField(default="None")
    encrypted = models.BooleanField(default=False)
    file = models.BinaryField(default=bin(0))
    timestamp = models.DateTimeField(default=datetime.now())
    owner = models.ForeignKey('users.User', on_delete=models.CASCADE)
"""

dev/secureshare/reports/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.db.models import Q
from django.conf import settings
from django.contrib import messages
from .search import *

from wsgiref.util import FileWrapper

import os
import zipfile

import tarfile
from io import BytesIO, StringIO

from .forms import *
from .models import *


def handle_uploaded_file(f, report, count, enc):
    f_upload = FileUpload(title=f.name, file=f, report=report, encrypted=enc)
    f_upload.save()
    new_name = str(f_upload.id)
    os.rename(f_upload.file.path, settings.MEDIA_ROOT + '/' + new_name)
    f_upload.file.name = new_name
    f_upload.save()


def register_report(request, folder_id):
    if request.method == 'POST':
        form = ReportForm(request.POST, request.FILES)
        if form.is_valid():
            report = Report(title=form.cleaned_data['title'], short_description=form.cleaned_data['short_description'],
                            detailed_description=form.cleaned_data['detailed_description'],
                            is_private=form.cleaned_data['is_private'],
                            owner=request.user, parent_folder=get_object_or_404(Folder, pk=folder_id))
            report.save()
            messages.success(request, "Report \""+form.cleaned_data['title']+"\" has been created.")
    return redirect('reports:view_folder', folder_id=folder_id)


def upload_file_to_report(request, report_id):
    report = get_object_or_404(Report, pk=report_id)
    if request.user.is_authenticated and not report.is_private or report.owner == request.user or request.user.is_site_manager:
        if request.method == 'POST':
            form = UploadFileForm(request.POST, request.FILES)
            if form.is_valid():
                enc = form.cleaned_data['encrypted']
                for count, f in enumerate(request.FILES.getlist('file_field')):
                    handle_uploaded_file(f, report, count, enc)
                for file in request.FILES.getlist('file_field'):
                    messages.success(request, "File \""+file.name+"\" has been uploaded.")
    return redirect('reports:view_report', pk=report_id)


def all_reports(request, detail='short'):

    template_name = "reports/all_reports.html"

    context = {}
    if request.user.is_authenticated:
        if request.user.is_site_manager:
            context['reports_list'] = Report.objects.all()
        else:
            context['reports_list'] = Report.objects.filter(Q(owner=request.user) | Q(is_private=False))
    else:
        context['reports_list'] = Report.objects.filter(is_private=False)
    context['detail'] = '/detail/' in request.path

    return render(request, template_name, context)


class MyReportListView(ListView):

    template_name = "reports/my_reports.html"
    model = Report

    def get_context_data(self, **kwargs):
        context = super(MyReportListView, self).get_context_data(**kwargs)
        context['reports_list'] = Report.objects.filter(parent_folder=self.request.user.root_folder)
        context['folder_list'] = SubFolder.objects.filter(parent_folder=self.request.user.root_folder)
        return context


class ReportDetailView(DetailView):

    template_name = "reports/view_report.html"
    model = Report

    def get_context_data(self, **kwargs):
        context = super(ReportDetailView, self).get_context_data(**kwargs)
        report = get_object_or_404(Report, pk=self.kwargs['pk'])
        report.view_count += 1
        report.save()
        context['file_list'] = FileUpload.objects.filter(report=report)
        context['favorited'] = self.request.user in report.favorited_by.all()
        return context


def edit_report(request, report_id):

    report = get_object_or_404(Report, pk=report_id)
    if request.user.is_authenticated and request.user.is_site_manager or request.user == report.owner:
        if request.method == "POST":
            report.title = request.POST['title']
            print(request.POST['sDesc'])
            print(request.POST['sDesc'][:200])
            report.short_description = request.POST['sDesc'][:200]
            report.detailed_description = request.POST['dDesc'][:5000]
            print(request.POST['privacy'])
            if request.POST['privacy'] == "p":
                report.is_private = True
            else:
                report.is_private = False
            report.save()
            messages.success(request, "Changes to \""+report.title+"\" have been saved.")
    return redirect(request.META['HTTP_REFERER'])


def delete_report(request, report_id):

    report = get_object_or_404(Report, pk=report_id)
    if request.user.is_authenticated and request.user.is_site_manager or request.user == report.owner:
        parent_folder_id = report.parent_folder.id
        title = report.title
        report.delete()
        messages.success(request, "Report \"" + title + "\" has been deleted.")
        return redirect('reports:view_folder', folder_id=parent_folder_id)
    return redirect('home:home')


def favorite_report(request, report_id):

    report = get_object_or_404(Report, pk=report_id)
    if report.has_access(request.user):
        if report in request.user.favorites.all():
            request.user.favorites.remove(report)
            messages.success(request, "Report \"" + report.title + "\" has been unfavorited.")
        else:
            request.user.favorites.add(report)
            messages.success(request, "Report \"" + report.title + "\" has been favorited.")
        return redirect(request.META['HTTP_REFERER'])
    return redirect('home:home')


def view_favorites(request):

    template_name = "reports/view_favorites.html"

    if request.user.is_authenticated:
        context = {}
        context['favorites_list'] = request.user.favorites.all()
        return render(request, template_name, context)
    return redirect('home:home')


def view_folder(request, folder_id):

    if int(request.user.root_folder.id) == int(folder_id):
        return redirect('reports:my_reports')

    template_name = 'reports/view_folder.html'
    folder = get_object_or_404(Folder, pk=folder_id)

    context = {}
    if not folder.is_root:
        folder = get_object_or_404(SubFolder, pk=folder_id)
        context['parent_folder'] = folder.parent_folder
    context['this_folder'] = folder
    context['reports_list'] = Report.objects.filter(parent_folder=folder)
    context['folder_list'] = folder.sub_folder.all()
    return render(request, template_name, context)


def new_folder(request, folder_id):

    if request.POST:
        if request.user.is_authenticated:
            current_folder = get_object_or_404(Folder, pk=folder_id)
            if current_folder.is_root:
                if request.user.is_site_manager or int(request.user.root_folder.id) == int(folder_id):
                    current_folder = get_object_or_404(RootFolder, pk=folder_id)
                    name = request.POST['name']
                    sub = SubFolder(name=name, owner=request.user, parent_folder=current_folder)
                    sub.save()
            else :
                current_folder = get_object_or_404(SubFolder, pk=folder_id)
                if current_folder.owner == request.user:
                    name = request.POST['name']
                    sub = SubFolder(name=name, owner=request.user, parent_folder=current_folder)
                    sub.save()
            messages.success(request, "Folder \"" + request.POST['name'] + "\" has been created.")
            return redirect(request.META['HTTP_REFERER'])
    return redirect('home:home')


def delete_folder(request, folder_id):

    folder = get_object_or_404(SubFolder, pk=folder_id)
    if request.user.is_site_manager or request.user == folder.owner:
        parent_folder_id = folder.parent_folder.id
        name = folder.name
        folder.delete()
        # add success message
        messages.success(request, "Folder \"" + name + "\" has been deleted.")
        return redirect('reports:view_folder', folder_id=parent_folder_id)
    return redirect('home:home')


def download_file(request, file_id):
    upload = get_object_or_404(FileUpload, pk=file_id)
    if request.user.is_authenticated and not upload.report.is_private or upload.report.owner == request.user or request.user.is_site_manager:
        file = upload.file
        response = HttpResponse(FileWrapper(file), content_type='application/force-download')
        response['Content-Disposition'] = 'attachment; filename="' + str(upload.title) + '"'
        return response
    return redirect('home:home')


def delete_file(request, file_id):
    upload = get_object_or_404(FileUpload, pk=file_id)
    if request.user.is_authenticated and upload.report.owner == request.user or request.user.is_site_manager:
        title = upload.title
        upload.delete()
        messages.success(request, "File \"" + title + "\" has been deleted.")
    return redirect(request.META['HTTP_REFERER'])


def download_report(request, report_id):
    report = get_object_or_404(Report, pk=report_id)
    # check permissions
    if request.user.is_authenticated and not report.is_private or report.owner == request.user or request.user.is_site_manager:
        uploads = FileUpload.objects.filter(report=report)
        out = BytesIO()
        tar = tarfile.open(report.title+'.tar.gz', mode="w:gz", fileobj = out)
        for upload in uploads:
            info = tarfile.TarInfo(name=upload.title)
            tar.addfile(tarinfo=info, fileobj=FileWrapper(upload.file))
        print(tar.getmembers())
        tar.close()

        response = HttpResponse(out.getvalue(), content_type='application/tgz')
        response['Content-Length'] = os.path.getsize(report.title+'.tar.gz')

dev/secureshare/reports/templates/reports/all_documents.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-xs-12 col-centered">
            {% if user.is_authenticated and user.is_site_manager %}
                <div class="list-group">
                    <li class="list-group-item list-group-item-info">
                        All Documents:
                        &nbsp;
                        <div class="btn-group btn-group-xs">
                            <a href="{% url 'reports:all_reports'%}" role="button" class="btn btn-default">
                                All Reports
                            </a>
                        </div>
                    </li>
                    {% if documents_list %}
                        {% for document in documents_list %}
                            <a href="{% url 'reports:view_report' pk=document.report.id %}" class="list-group-item list-group-item-action">
                                <span class="glyphicon glyphicon-file">&nbsp;</span>
                                {{ document.title }}
                                <!--{% if False %} document.is_encrypted-->
                                <!--<span class="pull-right glyphicon glyphicon-eye-close">&nbsp;</span>-->
                                <!--{% endif %}-->

                                <small><small>
                                    <span class="pull-right">
                                        {{ document.report.title }}
                                    </span>
                                </small></small>
                            </a>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item">There are no documents.</li>
                    {% endif %}
                </div>
            {% else %}
            <p>You must be a site manager to view documents.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

dev/secureshare/reports/templates/reports/all_reports.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-xs-12 col-centered">
            {% if user.is_authenticated %}
                <div class="list-group">
                    <li class="list-group-item list-group-item-info">
                        All Reports:
                        &nbsp;
                        <div class="btn-group btn-group-xs">
                            <a href="{% url 'reports:all_reports'%}" role="button" class="btn btn-default {% if not detail %}active{% endif %}">
                                Short
                            </a>
                            <a href="{% url 'reports:all_reports_detail' %}" role="button" class="btn btn-default {% if detail %}active{% endif %}">
                                Detail
                            </a>
                        </div>
                        {% if user.is_site_manager %}
                        <div class="btn-group btn-group-xs">
                            <a href="{% url 'reports:all_documents'%}" role="button" class="btn btn-default">
                                All Documents
                            </a>
                        </div>
                        {% endif %}
                        <a href="{% url 'reports:search' %}" class="pull-right">
                            <span class="glyphicon glyphicon-search">&nbsp;</span>
                        </a>
                    </li>
                    {% if reports_list %}
                        {% for report in reports_list %}
                            <a href="{% url 'reports:view_report' pk=report.id %}" class="list-group-item list-group-item-action">
                                <span class="glyphicon glyphicon-file">&nbsp;</span>
                                {{ report.title }}
                                {% if report.is_private %}
                                <span class="pull-right glyphicon glyphicon-eye-close">&nbsp;</span>
                                {% endif %}
                                {% if detail %}
                                <br>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <small><small>
                                    by
                                    <u>{{ report.owner.email }}</u>
                                    on
                                    {{ report.timestamp|date:'m/d/Y' }}
                                </small></small>
                                <br>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <small><small>
                                    {% if report.short_description %}
                                        {{ report.short_description }}
                                    {% else %}
                                        This report has no short description.
                                    {% endif %}
                                </small></small>
                                {% endif %}
                            </a>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item">There are no reports.</li>
                    {% endif %}
                </div>
            {% else %}
            <p>You must login to view reports.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

dev/secureshare/reports/templates/reports/view_report.html
{% extends 'home/base.html' %}

{% block content %}
<script type="text/javascript">
    function edit() {
        var editing = (document.getElementById('editing').value === "t");
        if (editing) { //create and submit form
            var title = document.getElementById('title').value;
            var sDesc = document.getElementById('sDesc').innerText;
            var dDesc = document.getElementById('dDesc').innerText;
            var privacy = document.getElementById('privacy').value;

            var action = document.getElementById('editingURL').value;
            var token = document.getElementsByName('csrfmiddlewaretoken')[0].value;

            var form = document.createElement("form");
            form.setAttribute("method", "POST");
            form.setAttribute("action", action);

            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", 'title');
            hiddenField.setAttribute("value", title);
            form.appendChild(hiddenField);

            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", 'sDesc');
            hiddenField.setAttribute("value", sDesc);
            form.appendChild(hiddenField);

            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", 'dDesc');
            hiddenField.setAttribute("value", dDesc);
            form.appendChild(hiddenField);

            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", 'privacy');
            hiddenField.setAttribute("value", privacy);
            form.appendChild(hiddenField);

            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", 'csrfmiddlewaretoken');
            hiddenField.setAttribute("value", token);
            form.appendChild(hiddenField);

            document.body.appendChild(form);
            form.submit();
        } else { // change input fields
            document.getElementById('editing').value = "t";
            document.getElementById('editButton').innerHTML = "Save Changes";
            document.getElementById('title').disabled="";
            document.getElementById('title').removeAttribute("class");
            document.getElementById('sDesc').contentEditable = true;
            document.getElementById('sDesc').style = "border:0.5px solid rgb(230, 230, 230);";
            document.getElementById('dDesc').contentEditable = true;
            document.getElementById('dDesc').style = "border:0.5px solid rgb(230, 230, 230);";
            document.getElementById('privacy').removeAttribute("disabled");
            document.getElementById('privacy').removeAttribute("class");
        }
    }

</script>
<style type="text/css">
    .input-no-style {
        border: none;
        background: transparent;
        color: #000;
    }
    .select-no-style {
        appearance: none;
        -webkit-appearance: none;
        -moz-appearance: none;
        border: none;
        /* needed for Firefox: */
        overflow:hidden;
        color: #000;
        background-color: inherit;
    }
</style>
    <div class="row">
        <div class="col-xs-12 col-centered">
            {% if user.is_authenticated %}
            {% if user.is_site_manager or user == report.owner or not report.is_private %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                          <button type="button" class="close" data-dismiss="alert">&times;</button>
                          <strong>Success!</strong>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="list-group">
                    <li class="list-group-item text-center">
                        <h2>
                            <span class="pull-left"><small>report:</small></span>
                            <input type="text" id="title" class="input-no-style" value="{{ report.title }}" disabled="disabled" maxlength="50"/>
                        </h2>
                    </li>
                    <li class="list-group-item">
                        <strong>Owner: </strong>{{ report.owner.email }}
                    </li>
                </div>
                <br>
                <div class="list-group">
                    <li class="list-group-item list-group-item-info">
                            <small><small>BACK TO:&nbsp;&nbsp;</small></small>
                            <a href="{% url 'reports:view_folder' folder_id=report.parent_folder.id %}" class="a-no-style">
                                {{ report.parent_folder.name }}
                            </a>
                    </li>
                    <li class="list-group-item">
                        This report is
                        <select id="privacy" class="select-no-style" disabled="disabled">
                            {% if report.is_private %}
                            <option value="np">not private</option>
                            <option value="p" selected>private</option>
                            {% else %}
                            <option value="np" selected>not private</option>
                            <option value="p">private</option>
                            {% endif %}
                        </select>
                    </li>
                    <li class="list-group-item">
                        <strong>Short Description: </strong>
                        <br>
                        <div id="sDesc" contenteditable="false" style="word-wrap:break-word;">
                            {{ report.short_description }}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <strong>Detailed Description: </strong>
                        <br>
                        <div id="dDesc" contenteditable="false" style="word-wrap:break-word;">
                            {{ report.detailed_description }}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <strong>View Count: </strong>
                        {{ report.view_count }}
                    </li>
                </div>
                <br>
                <div class="list-group">
                    <li class="list-group-item list-group-item-info">
                        Report content:
                        <a href='' data-toggle="modal" data-target="#uploadFileModal" class="pull-right">
                            <span class="glyphicon glyphicon-plus"></span>
                        </a>
                    </li>
                    {% if file_list %}
                        {% for file in file_list %}
                            <li class="list-group-item">
                            {{ file.title }}
                                    <a href="{% url 'reports:download_file' file_id=file.id %}" class="pull-right">
                                        <span class="glyphicon glyphicon-download-alt"></span>
                                    </a>
                                    {% if user.is_site_manager or user == report.owner %}
                                         <a href="{% url 'reports:delete_file' file_id=file.id %}" class="pull-right">
                                             <span class="glyphicon glyphicon-trash">&nbsp;&nbsp;</span>
                                         </a>
                                    {% endif %}
                                    {% if file.encrypted %}
                                        <span class="pull-right glyphicon glyphicon-sunglasses">&nbsp;&nbsp;</span>
                                    {% endif %}
                            </li>
                        {% endfor %}
                    {% endif %}
                </div>
                <br>
                {% if user.is_site_manager or user == report.owner %}
                    <a href="{% url 'reports:delete_report' report_id=report.id %}" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-trash"></span></a>

                    <button onclick="edit()" id="editButton" class="btn btn-info pull-right" style="margin-right:8px;"><span class="glyphicon glyphicon-pencil"></span></button>
                    <input type="hidden" id="editing" value="f">
                    <input type="hidden" id="editingURL" value="{% url 'reports:edit_report' report_id=report.id %}">
                    {% csrf_token %}
                {% endif %}
                <a href="{% url 'reports:favorite_report' report_id=report.id %}" class="btn btn-warning pull-right" style="margin-right:8px;{% if favorited %}color:black;{% endif %}"><span class="glyphicon glyphicon-star"></span></a>
            {% else %}
            <p>You do not have permission to view this page.</p>
            {% endif %}
            {% else %}
            <p>You must login to view this page.</p>
            {% endif %}

        </div>
    </div>

<div class="modal fade" id="uploadFileModal" role="dialog">
    <div class="modal-dialog">
          <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="border-bottom: none;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New Upload</h4>
            </div>
            <form action="{% url 'reports:upload_file_to_report' report_id=report.id %}" method="post" enctype="multipart/form-data">
            <div class="modal-body">
                {% csrf_token %}
                <label for="id_file_field">Upload files</label><input id="id_file_field" name="file_field" type="file" multiple />
                <br>
                <label for="id_encrypted">Encrypted?</label> <input id="id_encrypted" name="encrypted" type="checkbox" />
            </div>
            <div class="modal-footer" style="border-top: none;">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <input type="submit" value="Upload" class="btn btn-primary">
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}