dev/secureshare/home/urls.py
from django.conf.urls import include, url

from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView, name='home'),
]

dev/secureshare/reports/urls.py
from django.conf.urls import include, url

from . import views


urlpatterns = [
    url(r'^register/(?P<folder_id>[0-9]+)/$', views.register_report, name='register_report'),

    url(r'^file/download/(?P<file_id>[0-9]+)/$', views.download_file, name='download_file'),
    url(r'^file/delete/(?P<file_id>[0-9]+)/$', views.delete_file, name='delete_file'),
    url(r'^file/all_documents/$', views.all_documents, name='all_documents'),

    url(r'^report/(?P<pk>[0-9]+)/$', views.ReportDetailView.as_view(), name='view_report'),
    url(r'^report/(?P<report_id>[0-9]+)/edit/$', views.edit_report, name='edit_report'),
    url(r'^report/(?P<report_id>[0-9]+)/delete/$', views.delete_report, name='delete_report'),
    url(r'^report/(?P<report_id>[0-9]+)/download/$', views.download_report, name='download_report'),
    url(r'^report/(?P<report_id>[0-9]+)/upload_file/$', views.upload_file_to_report, name='upload_file_to_report'),
    url(r'^report/(?P<report_id>[0-9]+)/favorite/$', views.favorite_report, name='favorite_report'),

    url(r'^folder/(?P<folder_id>[0-9]+)/$', views.view_folder, name='view_folder'),
    url(r'^folder/(?P<folder_id>[0-9]+)/new/$', views.new_folder, name='new_folder'),
    url(r'^folder/(?P<folder_id>[0-9]+)/delete/$', views.delete_folder, name='delete_folder'),

    url(r'^all_reports/$', views.all_reports, name='all_reports'),
    url(r'^all_reports/detail/$', views.all_reports, name='all_reports_detail'),
    url(r'^my_reports/$', views.MyReportListView.as_view(), name='my_reports'),
    url(r'^favorites/$', views.view_favorites, name='view_favorites'),
    url(r'^search/$', views.search, name='search'),
]

dev/secureshare/secureshare/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^messages/', include('postman.urls', namespace='postman')),
]

dev/secureshare/users/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'users:login'}, name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^change_password/$', change_password, name='change-password'),



    url(r'^create_group/$', create_group, name='create_group'),
    url(r'^join_group/$', join_group, name='join_group'),
    url(r'^leave_group/$', leave_group, name='leave_group'),
    #url(r'^invite/$', invite_user, name='invite_user'),


    url(r'^all_users/$', all_users, name='all_users'),
    url(r'^all_groups/$', all_groups, name='all_groups'),
    url(r'^my_groups/$', my_groups, name='my_groups'),

    url(r'^user/(?P<user_id>[0-9]+)/$', view_user, name='user'),
    url(r'^group/(?P<group_id>[0-9]+)/$', view_group, name='group'),

    url(r'^group/(?P<group_id>[0-9]+)/leave/(?P<user_id>[0-9]+)/$', leave_group_by_id, name='leave_group_by_id'),

    url(r'^user/(?P<user_id>[0-9]+)/suspend/$', suspend_user, name='suspend_user'),
    url(r'^user/(?P<user_id>[0-9]+)/promote/$', promote_user, name='promote_user'),
    url(r'^user/(?P<user_id>[0-9]+)/(?P<group_id>[0-9]+)/remove_from_group/$', remove_user_from_group, name='remove_user_from_group'),
    url(r'^user/(?P<group_id>[0-9]+)/add_user_to_group/$', add_user_to_group, name='add_user_to_group'),

]

'''
url(r'^inbox/$', inbox, name='inbox'),
url(r'^outbox/$', outbox, name='outbox'),
url(r'^send_message/$', send_message, name='send_message'),
'''

dev/secureshare/home/models.py
from django.db import models

# Create your models here.

dev/secureshare/home/views.py
from django.shortcuts import render

# Create your views here.


def HomeView(request):
    template_name='home/home.html'
    return render(request, template_name)

dev/secureshare/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!--&lt;!&ndash; Latest compiled and minified JavaScript &ndash;&gt;-->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<!-- More CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>

{% block css %}
{% endblock %}

<head>
    <title>SecureFileShare</title>
    <style>
        body {
            padding-top: 90px;
            background-color: #888888;
        }
        /** {*/
            /*-webkit-border-radius: 0 !important;*/
            /*-moz-border-radius: 0 !important;*/
              /*border-radius: 0 !important;*/
        /*}*/
        .col-centered {
            float: none;
            margin: 0 auto;
        }
        .a-no-style {
            text-decoration: none;
            color: inherit;
        }
        .a-no-style:hover {
            color: inherit;
        }
    </style>
</head>
    <body>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href={% url 'home:home' %}>SecureFileShare</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% load i18n static %}{% load postman_tags %}
                {% postman_unread as unread_count %}
                {% if user.is_authenticated %}
                    <li class="dropdown">
                          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reports</a>
                          <ul class="dropdown-menu">
                                <li><a href="{% url 'reports:my_reports' %}">My Reports</a></li>
                                <li><a href="{% url 'reports:view_favorites' %}">Favorites</a></li>
                                <li><a href="{% url 'reports:all_reports' %}">All Reports</a></li>
                          </ul>
                    </li>
                    <li class="dropdown">
                          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Groups</a>
                          <ul class="dropdown-menu">
                              <li><a href="{% url 'users:my_groups' %}">My Groups</a></li>
                              {% if user.is_site_manager %}
                              <li><a href="{% url 'users:all_groups' %}">All Groups</a></li>
                              {% endif %}
                          </ul>
                    </li>

                    <li><a href="{% url 'postman:inbox' %}">Messages{% if unread_count %} <strong>({{ unread_count }})</strong>{% endif %}</a></li>

                    {% if user.is_site_manager %}
                    <li><a href="{% url 'users:all_users' %}">Users</a></li>
                    {% endif %}

                    <li class="dropdown">
                          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                              <span class="glyphicon glyphicon-user"></span>
                          </a>
                          <ul class="dropdown-menu">
                              <li><a href="{% url 'users:change-password' %}">Change Passowrd</a></li>
                              <li><a href={% url 'users:logout' %}>Logout</a></li>
                          </ul>
                    </li>
                {% else %}
                    <li><a href={% url 'users:login' %}>Login</a></li>

                {% endif %}
            </ul>
            </div><!--/.nav-collapse -->
        </div>
        </nav>

        <div class="col-sm-8 col-md-8 col-lg-8 col-centered">
            {% block content %}
            {% endblock %}
        </div>

       {% block js %}
       <!-- Bootstrap core JavaScript
       ================================================== -->
       <!-- Placed at the end of the document so the pages load faster -->
       {% endblock %}
    </body>
</html>

dev/secureshare/home/templates/home/home.html
{% extends 'home/base.html' %}

{% block content %}
  <div class="row">
    <div class="col-sm-8 col-md-8 col-lg-8 col-centered">
        {% if user.is_authenticated %}
        {% load i18n static %}{% load postman_tags %}
        {% postman_unread as unread_count %}
        <h1>Hello, {{ user.first_name }}!</h1>

        {% else %}
        <a href="{% url 'users:login' %}" role="button" class="btn btn-success btn-lg btn-block">Login</a>

        {% endif %}
    </div>
  </div>
{% endblock %}